### Creacion evento
POST {{base}}/api/events
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Taller de Escultura",
  "description": "Se realizará un taller de escultura en la Plaza de Tigre",
  "address": "Av Siempre Viva 268, Tigre, Provincia de Buenos Aires",
  "startDate": "2024-12-15 11:45",
  "endDate": "2024-12-29 11:45",
  "category": "EDUCATIVE",
  "audience": "PUBLIC"
}

### Consultar evento
GET {{base}}/api/events/cea268b5-1591-4dbe-b72e-77e7ecdad0fc
Authorization: Bearer {{token}}

### Consultar eventos del usuario autenticado
GET {{base}}/api/events/me?page=0&size=10
Authorization: Bearer {{token}}

### Consultar eventos de un usuario por nombre de usuario
GET {{base}}/api/events/user/bocelli.andrea?page=0&size=10
Authorization: Bearer {{token}}

### Consultar eventos
GET {{base}}/api/events?q=&page=0&size=10&sort=name,asc
Authorization: Bearer {{token}}


### Modificar evento
PATCH {{base}}/api/events/3dbc881f-6802-454f-aea0-a1a423c54a8b
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Taller de Ceramica",
  "description": "Se realizará un taller de cerámica en la Plaza San Martín",
  "address": "Av Daniel M. Cazon 1220, Tigre, Provincia de Buenos Aires",
  "start": "02/12/24",
  "end": "09/12/24",
  "category": "EDUCATIVE",
  "audience": "PUBLIC"
}

### Eliminar evento
DELETE {{base}}/api/events/3dbc881f-6802-454f-aea0-a1a423c54a8b
Authorization: Bearer {{token}}

