### Creación publicación
POST {{base}}/api/posts
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "originalPoster": "bocelli.andrea",
  "audience": "CITY",
  "title": "Post 1 (RequestBody)",
  "subtype": 1,
  "description": "Descripcion 1 Ejemplo (RequestBody)",
  "neighbourhood": 1,
  "timestamp": "2024-10-01T12:30:00Z",
  "tags": "ejemplo,requestbody,requestbody2"
}

### Consultar publicaciones
GET {{base}}/api/posts/all?page=0&size=10&activeOnly=true
Authorization: Bearer {{token}}

### Buscar ciudades, orden ascendente según título
GET {{base}}/api/posts/search?q=&page=0&size=10&sort=title,asc
Authorization: Bearer {{token}}

### Buscar ciudades, orden descendente según título
GET {{base}}/api/posts/search?q=&page=0&size=10&sort=title,desc
Authorization: Bearer {{token}}

### Consultar publicación
GET {{base}}/api/posts/1
Authorization: Bearer {{token}}

### Consultar publicaciones según autor
GET {{base}}/api/posts/op/1
Authorization: Bearer {{token}}

### Consultar publicaciones según audiencia
GET {{base}}/api/posts/audience/CITY
Authorization: Bearer {{token}}

### Consultar publicaciones según tipo
GET {{base}}/api/posts/type/1
Authorization: Bearer {{token}}

### Consultar publicaciones según subtipo
GET {{base}}/api/posts/subtype/1
Authorization: Bearer {{token}}

### Consultar publicaciones según rango de fecha
GET {{base}}/api/posts/date/2024-09-28/2024-09-30
Authorization: Bearer {{token}}

### Consultar publicaciones según fecha de inicio
GET {{base}}/api/posts/date-start/2024-09-30
Authorization: Bearer {{token}}

### Consultar publicaciones según fecha de fin
GET {{base}}/api/posts/date-end/2024-09-30
Authorization: Bearer {{token}}

### Editar datos básicos de la publicación
PATCH {{base}}/api/posts/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Post 2 (RequestBody)",
  "subtype": 1,
  "description": "Descripcion 2 Ejemplo (RequestBody)",
  "neighbourhood": 1,
  "tags": "ejemplo,requestbody,requestbody2,requestbody3"
}

### Deshabilitar publicación
DELETE {{base}}/api/posts/1
Authorization: Bearer {{token}}