### Crear una cuenta de usuario
POST {{base}}/api/signup
Content-Type: application/json

{
  "name": "Andrea Bocelli",
  "username": "bocelli.andrea",
  "password": "123456789"
}


### Iniciar sesión
POST {{base}}/api/login
Content-Type: application/json

{
  "username": "mockUser0001",
  "password": "P455w0&d+"
}





### Iniciar sesión con TOTP
POST {{base}}

{
  "username": "bocelli.andrea",
  "password": "Abc.1234$6789"
}

### Solicitar código de verificación de correo electrónico
POST {{base}}/api/users/me/mail
Authorization: Bearer {{token}}

maximo.tomas.can.edo@gmail.com


### Verificar correo electrónico con código OTP recibido
POST {{base}}/api/users/me/mail/verify
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "subject": "maximo.tomas.can.edo@gmail.com",
  "code": "906553"
}


### Solicitar código de verificación de número de teléfono
POST {{base}}/api/users/me/phone
Authorization: Bearer {{token}}

+541130388784


### Verificar número de teléfono con código OTP recibido
POST {{base}}/api/users/me/phone/verify
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "subject": "+541130388784",
  "code": "111111"
}


### Consultar usuario autenticado
GET {{base}}/api/users/me
Authorization: Bearer {{token}}


### Consultar por otro usuario (*)
GET {{base}}/api/users/root
Authorization: Bearer {{token}}


### Editar datos básicos del usuario
PATCH {{base}}/api/users/me
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Máximo Bocelli",
  "address": "Av. Siempreviva 723"
}


### Editar datos básicos (*)
PATCH {{base}}/api/users/root
Authorization: Bearer {{token}}


### Actualizar contraseña
POST {{base}}/api/users/me/password
Authorization: Bearer {{token}}

Abc.1234$6789


### Deshabilitar el usuario autenticado (*)
DELETE {{base}}/api/users/me
Authorization: Bearer {{token}}


### Deshabilitar usuario (*)
DELETE {{base}}/api/users/bocelli.andrea
Authorization: Bearer {{token}}


### Búsqueda de usuarios
GET {{base}}/api/users?q=&page=0&size=10&sort=name,asc
Authorization: Bearer {{token}}